### ISSUE TITLE
print(blocklayer), print(svgcontent) and some other prints cause error

### ISSUE THREAD

**Issue by MioNya4** [KnowZero/Krita-LazyTextTool-Prototype#2]
UnicodeEncodeError: 'ascii' codec can't encode character '\u0444' in position 319: ordinal not in range(128)

**Comment by MioNya4** [comment]
temporary solution:
def print(*args):
    return
at the beginning of LazyTextToolFunc.py file

**Comment by KnowZero** [comment]
I removed the prints, see if it works fine for you.

Also, if you aren't doing anything too fancy with text, you may want to try 5.3 nightlies which include a native on canvas text tool
